FD: true
Hungarian: false
MLP_A_layers: 3
MLP_F_fd_layers: 1
MLP_F_layers: 1
MLP_h_layers: 1
Mmax: 10
alpha_A: 1
alpha_F: 1
alpha_F_fd: 1
alpha_h: 1
augment_data: true
batchsize: 128
dataset: ColoringSmall
dataset_size: -1
device: cuda
dropout: 0.0
linear_matching: false
lr: 0.0003
mask_self_loops: false
max_grad_norm: 0.1
max_grad_step: 100000
max_iter: 20
max_iter_inner: 1000
model_dim: 256
n_eval_interval: 1000
node_feature_dim: 4
pre_norm: true
run_name: ColoringSmall
symmetric: true
task: Img2Graph
tol: 1.0e-05
transformer_dropout: 0.0
transformer_heads: 4
transformer_layers: 4
virtual_node: true
wandb: true
warmup: 8000
